//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string TaskContent { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual TaskPriority TaskPriority { get; set; }
        public virtual TaskStatus TaskStatu { get; set; }
    }
}
